# -*- coding: utf-8 -*-
"""Untitled6 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_rFZ5BQFUhfX6WsZSLHVC98sU4iZkFI
"""

# -*- coding: utf-8 -*-
"""Experimental.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sakgMfi7rWd_pO6fIB1zYbAVN1TlxzGk

Открываем исходный файл и файл с клиппингом.

*   wav_file_path - путь до исходного файла (без клиппинга), его данные записываются в массив samples
*   wav_file_path1 - путь до файла с клиппингом, его данные записываются в массив samples1
"""
import traceback
import warnings
import sys

def warn_with_traceback(message, category, filename, lineno, file=None, line=None):

    log = file if hasattr(file,'write') else sys.stderr
    traceback.print_stack(file=log)
    log.write(warnings.formatwarning(message, category, filename, lineno, line))

warnings.showwarning = warn_with_traceback
warnings.simplefilter("always")

import os

os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'


wav_file_path = "lecture_lngf.rf64"
wav_file_path1 = "lecture_lngfс.rf64"
import wave
import struct
import numpy as np
from tensorflow.keras import backend as K
from tensorflow.keras.utils import Sequence


def scheduler(epoch, lr):
    if epoch < 50:
        return lr
    else:
        return lr * 0.95

def get_rf64_sample_count(filename: str) -> int:
    """
    Returns the total number of sample frames in an RF64 file.
    This function only reads header information (including the ds64 chunk)
    without loading the entire file into RAM.
    """
    with open(filename, "rb") as f:
        # Read first 12 bytes: "RF64", file size placeholder, and "WAVE"
        header = f.read(12)
        if header[0:4] != b"RF64":
            raise ValueError("Not an RF64 file.")
        
        # Iterate through chunks until the ds64 chunk is found.
        while True:
            chunk_id = f.read(4)
            if not chunk_id:
                raise ValueError("Reached EOF without finding ds64 chunk.")
            chunk_size_bytes = f.read(4)
            if len(chunk_size_bytes) < 4:
                raise ValueError("Incomplete chunk header encountered.")
            chunk_size = struct.unpack("<I", chunk_size_bytes)[0]
            
            if chunk_id == b"ds64":
                ds64_data = f.read(chunk_size)
                # ds64 chunk should contain at least 24 bytes:
                # 8 bytes for riffSize, 8 bytes for dataSize, and 8 bytes for sampleCount.
                if len(ds64_data) < 24:
                    raise ValueError("Incomplete ds64 chunk data.")
                # sampleCount is located at byte offset 16 in the ds64 data.
                sample_count = struct.unpack("<Q", ds64_data[16:24])[0]
                return sample_count
            else:
                # Skip over this chunk.
                f.seek(chunk_size, 1)


def read_rf64_samples(filename: str, start_index: int, end_index: int) -> list:
    """
    Reads and returns a sequence of samples from an RF64 file as a list of normalized floating-point values 
    in the range [-1, 1]. The sample values are returned as a list of lists (one per sample frame), where 
    each inner list contains values for each channel.
    
    The function reads only the required data from the "data" chunk (without loading the full file into RAM)
    and assumes:
      - The file is PCM encoded (either standard or extensible PCM).
      - start_index and end_index are indices of sample frames (start inclusive, end exclusive).
      - The "fmt " chunk appears before the "data" chunk.
    """
    if start_index < 0 or end_index <= start_index:
        raise ValueError("Invalid sample indices provided.")
    
    with open(filename, "rb") as f:
        # Read initial 12 bytes: "RF64", file size placeholder, and "WAVE"
        header = f.read(12)
        if header[0:4] != b"RF64":
            raise ValueError("Not an RF64 file.")
        
        # Skip ds64 chunk (assumed to be the first chunk)
        while True:
            chunk_id = f.read(4)
            if not chunk_id:
                raise ValueError("Reached EOF without finding ds64 chunk.")
            chunk_size_bytes = f.read(4)
            if len(chunk_size_bytes) < 4:
                raise ValueError("Incomplete chunk header encountered.")
            chunk_size = struct.unpack("<I", chunk_size_bytes)[0]
            if chunk_id == b"ds64":
                f.seek(chunk_size, 1)
                break
            else:
                f.seek(chunk_size, 1)
        
        # Locate the "fmt " chunk to determine audio format, block alignment, and bits per sample.
        fmt_found = False
        block_align = None
        num_channels = None
        bits_per_sample = None
        
        while not fmt_found:
            chunk_id = f.read(4)
            if not chunk_id:
                raise ValueError("Reached EOF without finding fmt chunk.")
            chunk_size_bytes = f.read(4)
            if len(chunk_size_bytes) < 4:
                raise ValueError("Incomplete chunk header encountered.")
            chunk_size = struct.unpack("<I", chunk_size_bytes)[0]
            
            if chunk_id == b"fmt ":
                fmt_data = f.read(chunk_size)
                if len(fmt_data) < 16:
                    raise ValueError("Incomplete fmt chunk.")
                # Unpack first 16 bytes: AudioFormat (H), NumChannels (H), SampleRate (I),
                # ByteRate (I), BlockAlign (H), BitsPerSample (H)
                audio_format, num_channels, sample_rate, byte_rate, block_align, bits_per_sample = \
                    struct.unpack("<HHIIHH", fmt_data[:16])
                
                if audio_format == 1:
                    # Standard PCM
                    pass
                elif audio_format == 0xfffe:
                    # WAVE_FORMAT_EXTENSIBLE
                    if len(fmt_data) < 40:
                        raise ValueError("Incomplete WAVE_FORMAT_EXTENSIBLE fmt chunk.")
                    # Unpack extended fields: cbSize (H), wValidBitsPerSample (H),
                    # dwChannelMask (I), SubFormat (16s)
                    cbSize, validBitsPerSample, channelMask, subformat = struct.unpack("<HHI16s", fmt_data[16:40])
                    # Expected PCM GUID for extensible format (little-endian):
                    pcm_guid = b'\x01\x00\x00\x00\x00\x00\x10\x00\x80\x00\x00\xAA\x00\x38\x9B\x71'
                    if subformat != pcm_guid:
                        raise ValueError("Only PCM encoded files are supported (extensible subformat mismatch).")
                    # Use the valid bits per sample for normalization.
                    bits_per_sample = validBitsPerSample
                else:
                    raise ValueError("Only PCM encoded files are supported.")
                fmt_found = True
            else:
                f.seek(chunk_size, 1)
        
        if block_align is None or num_channels is None or bits_per_sample is None:
            raise ValueError("Audio format information not found.")
        
        # Locate the "data" chunk.
        data_found = False
        while not data_found:
            chunk_header = f.read(8)
            if len(chunk_header) < 8:
                raise ValueError("Reached EOF without finding data chunk.")
            chunk_id = chunk_header[0:4]
            chunk_size = struct.unpack("<I", chunk_header[4:8])[0]
            if chunk_id == b"data":
                data_start = f.tell()
                data_found = True
            else:
                f.seek(chunk_size, 1)
        
        # Calculate byte offset and number of bytes to read for the requested sample frames.
        offset = start_index * block_align
        num_frames = end_index - start_index
        num_bytes = num_frames * block_align
        
        # Seek to the beginning of the desired sample segment and read the sample data.
        f.seek(data_start + offset)
        sample_bytes = f.read(num_bytes)
        if len(sample_bytes) != num_bytes:
            raise ValueError("Could not read the requested number of sample bytes.")
    
    # Convert raw bytes to a NumPy array based on bits per sample.
    if bits_per_sample == 8:
        # 8-bit PCM is usually unsigned.
        dtype = np.uint8
        samples = np.frombuffer(sample_bytes, dtype=dtype).astype(np.float32)
        # Normalize: convert range from [0, 255] to [-1, 1]
        samples = (samples - 128) / 128.0
    elif bits_per_sample == 16:
        dtype = np.int16
        samples = np.frombuffer(sample_bytes, dtype=dtype).astype(np.float32)
        samples = samples / 32768.0
    elif bits_per_sample == 32:
        dtype = np.int32
        samples = np.frombuffer(sample_bytes, dtype=dtype).astype(np.float32)
        samples = samples / 2147483648.0
    else:
        raise ValueError(f"Unsupported bits per sample: {bits_per_sample}")
    
    # Reshape the 1D array to a 2D array (num_frames, num_channels)
    try:
        samples = samples.reshape(-1, num_channels)
    except Exception as e:
        raise ValueError("Mismatch in number of samples and channel count.") from e
    
    # Return the normalized samples as a list of lists.
    return samples.tolist()

def read_wav_as_float(file_path):
    """
    Reads a WAV file and returns its samples as a NumPy array of float32 values.

    Parameters:
        file_path (str): Path to the WAV file.

    Returns:
        np.ndarray: An array of float32 samples in the range [-1.0, 1.0].
    """
    with wave.open(file_path, 'rb') as wav_file:
        # Get parameters
        n_channels = wav_file.getnchannels()
        sample_width = wav_file.getsampwidth()
        n_frames = wav_file.getnframes()
        frame_rate = wav_file.getframerate()
        print(f"Channels: {n_channels}, Sample Width: {sample_width}, Frame Rate: {frame_rate}, Frames: {n_frames}")

        # Read frames as bytes
        raw_data = wav_file.readframes(n_frames)

    # Determine the data type based on sample width
    dtype = {1: np.int8, 2: np.int16, 4: np.int32}.get(sample_width)
    if dtype is None:
        raise ValueError(f"Unsupported sample width: {sample_width}")

    # Convert raw bytes to numpy array without copying data
    int_data = np.frombuffer(raw_data, dtype=dtype)

    # Convert to float32 and normalize to range [-1.0, 1.0]
    max_val = float(2 ** (8 * sample_width - 1))
    float_data = int_data.astype(np.float32) / max_val

    # Handle multi-channel audio by averaging channels
    if n_channels > 1:
        float_data = float_data.reshape(-1, n_channels).mean(axis=1)

    return float_data

"""Функция для записи массива в файл по пути output_path."""

def write_float_samples_to_wav(samples, sample_rate, output_path):
    """
    Writes floating-point audio samples to a mono 16-bit WAV file.

    Parameters:
        samples (list or np.ndarray): Array of floating-point audio samples in the range [-1.0, 1.0].
        sample_rate (int): Sample rate of the audio in Hz (e.g., 44100).
        output_path (str): Path to save the output WAV file.
    """
    # Ensure the samples are a NumPy array
    samples = np.array(samples, dtype=np.float32)

    # Clip the samples to the range [-1.0, 1.0] to prevent overflow
    samples = np.clip(samples, -1.0, 1.0)

    # Convert to 16-bit PCM format
    int_samples = (samples * 32767).astype(np.int16)

    # Write to a WAV file
    with wave.open(output_path, 'wb') as wav_file:
        # Set the parameters for the WAV file
        wav_file.setnchannels(1)  # Mono
        wav_file.setsampwidth(2)  # 16-bit PCM
        wav_file.setframerate(sample_rate)

        # Write the audio frames
        wav_file.writeframes(int_samples.tobytes())

class AudioDataGenerator(Sequence):
    """
    A Keras Sequence for generating batches of overlapping audio sequences.
    
    Instead of reading many small segments from disk, this generator caches chunks
    of 100,000 samples (plus extra samples to cover sequences that start near the end
    of the chunk). It then extracts full sequences (of length SQNC_LENGTH) from these chunks.
    """
    def __init__(self, original_file, clipped_file, SQNC_LENGTH, batch_size=32, cache_size=100, shuffle=True):
        self.original_file = original_file
        self.clipped_file = clipped_file
        self.SQNC_LENGTH = SQNC_LENGTH
        self.batch_size = batch_size
        self.cache_size = cache_size  # number of samples to cache per chunk (starting positions)
        self.nofsamples = get_rf64_sample_count(original_file)
        self.step_size = SQNC_LENGTH // 2  # 50% overlap
        # Precompute global starting indices for full sequences.
        self.global_indices = list(range(0, self.nofsamples - SQNC_LENGTH + 1, self.step_size))
        self.shuffle = shuffle
        if self.shuffle:
            np.random.shuffle(self.global_indices)
    
    def __len__(self):
        return int(np.ceil(len(self.global_indices) / self.batch_size))
    
    def __getitem__(self, idx):
        # Get global sequence starting indices for this batch.
        batch_global_indices = self.global_indices[idx * self.batch_size : (idx + 1) * self.batch_size]
        
        # Group the batch indices by the chunk they belong to.
        # Here, we define the chunk number as:
        #    chunk_num = global_index // cache_size
        # and we will load from:
        #    chunk_start = chunk_num * cache_size
        #    chunk_end   = min(nofsamples, chunk_start + cache_size + SQNC_LENGTH - 1)
        chunk_groups = {}
        for g in batch_global_indices:
            chunk_num = g // self.cache_size
            local_index = g - (chunk_num * self.cache_size)
            if chunk_num not in chunk_groups:
                chunk_groups[chunk_num] = []
            chunk_groups[chunk_num].append(local_index)
        
        X_batch = []
        y_batch = []
        
        # For each chunk, load the large block and extract sequences.
        for chunk_num, local_indices in chunk_groups.items():
            chunk_start = chunk_num * self.cache_size
            # Load extra SQNC_LENGTH-1 samples so that sequences starting at the end of the chunk are complete.
            chunk_end = min(self.nofsamples, chunk_start + self.cache_size + self.SQNC_LENGTH - 1)
            
            # Read the chunk from the files. These functions return a list (or array) of sample frames.
            clipped_chunk = read_rf64_samples(self.clipped_file, chunk_start, chunk_end)
            original_chunk = read_rf64_samples(self.original_file, chunk_start, chunk_end)
            
            # Extract sequences from this chunk.
            for li in local_indices:
                # Ensure that the extracted sequence has exactly SQNC_LENGTH frames.
                if li + self.SQNC_LENGTH > len(clipped_chunk):
                    # This situation should not happen because global indices were computed
                    # to allow a full sequence, but guard just in case.
                    continue
                X_seq = clipped_chunk[li : li + self.SQNC_LENGTH]
                y_seq = original_chunk[li : li + self.SQNC_LENGTH]
                X_batch.append(X_seq)
                y_batch.append(y_seq)
        
        # Convert lists to numpy arrays. Each element should now have uniform shape.
        return np.array(X_batch), np.array(y_batch)
    
    def on_epoch_end(self):
        if self.shuffle:
            np.random.shuffle(self.global_indices)

"""Обучение нейросети на множестве спектрограмм сигнала. N и M - количество точек по осям частоты и времени соответственно в обучающих выборках."""

import tensorflow as tf
FSTEP = 8
# Custom STFT layer using tf.signal.stft
class STFTLayer(tf.keras.layers.Layer):
    def __init__(self, frame_length=8, frame_step=4, **kwargs):
        super(STFTLayer, self).__init__(**kwargs)
        self.frame_length = frame_length
        self.frame_step = frame_step

    def call(self, inputs):
        # inputs: shape (batch, sq_lngth)
        # Use a Hann window
        window = tf.signal.hann_window(self.frame_length, dtype=inputs.dtype)
        stft_result = tf.signal.stft(
            inputs,
            frame_length=self.frame_length,
            frame_step=self.frame_step,
            window_fn=lambda fl, dtype: window
        )
        # tf.signal.stft returns shape (batch, time_frames, fft_unique_bins)
        # For our design, we want to use (batch, fft_unique_bins, time_frames)
        magnitude = tf.abs(stft_result)
        phase = tf.math.angle(stft_result)
        # Transpose to shape (batch, fft_unique_bins, time_frames)
        magnitude = tf.transpose(magnitude, perm=[0, 2, 1])
        phase = tf.transpose(phase, perm=[0, 2, 1])
        return magnitude, phase

    def compute_output_shape(self, input_shape):
        batch = input_shape[0]
        if input_shape[1] is None:
            return (batch, None, None), (batch, None, None)
        # time_frames computed from signal length:
        time_frames = (input_shape[1] - self.frame_length) // self.frame_step + 1
        fft_bins = self.frame_length // 2 + 1
        # After transposition, output shape becomes (batch, fft_bins, time_frames)
        return (batch, fft_bins, time_frames), (batch, fft_bins, time_frames)


# Custom inverse STFT layer using tf.signal.inverse_stft
class ISTFTLayer(tf.keras.layers.Layer):
    def __init__(self, frame_length=8, frame_step=4, sq_lngth=None, **kwargs):
        super(ISTFTLayer, self).__init__(**kwargs)
        self.frame_length = frame_length
        self.frame_step = frame_step
        self.sq_lngth = sq_lngth

    def call(self, inputs):
        # inputs: a list [mag, phase] with shapes (batch, F, T)
        mag, phase = inputs
	# tf.signal.inverse_stft expects input of shape (batch, time_frames, fft_unique_bins).
	# So transpose mag and phase from (batch, F, T) to (batch, T, F):
        mag_t = tf.transpose(mag, perm=[0, 2, 1])
        phase_t = tf.transpose(phase, perm=[0, 2, 1])
        phase_float = tf.cast(phase_t, tf.float32)
        stft_complex = tf.cast(mag_t, tf.complex64) * tf.complex(tf.cos(phase_float), tf.sin(phase_float))
        #stft_complex = tf.cast(mag_t, tf.complex64) * tf.exp(1j * tf.cast(phase_t, tf.complex64))
        window = tf.signal.hann_window(self.frame_length, dtype=tf.float32)
        reconstructed = tf.signal.inverse_stft(
            stft_complex,
            frame_length=self.frame_length,
            frame_step=self.frame_step,
            window_fn=lambda fl, dtype: window
        )
        if self.sq_lngth is not None:
            reconstructed = reconstructed[:, :self.sq_lngth]
        return reconstructed

    def compute_output_shape(self, input_shape):
        batch = input_shape[0][0]
        if self.sq_lngth is not None:
            return (batch, self.sq_lngth)
        else:
            return (batch, None)


# Helper layers to add and remove a singleton channel dimension.
class AddInnerDim(tf.keras.layers.Layer):
    def call(self, x):
        return tf.expand_dims(x, axis=-1)

class Squeeze(tf.keras.layers.Layer):
    def call(self, x):
        return tf.squeeze(x, axis=-1)

# Custom layer wrapping the entire spectrogram processing pipeline.
class SpectrogramModelLayer(tf.keras.layers.Layer):
    def __init__(self, sq_lngth, **kwargs):
        super(SpectrogramModelLayer, self).__init__(**kwargs)
        self.sq_lngth = sq_lngth
        self.frame_step = FSTEP
        self.frame_length = FSTEP * 2  # e.g. if FSTEP=8 then frame_length=16
        # Frequency bins: frame_length//2 + 1 = FSTEP+1 (e.g. 9 if FSTEP=8)
        self.F_const = self.frame_step + 1  
        # Time frames computed from signal length:
        self.M_const = (sq_lngth - self.frame_length) // self.frame_step + 1

        # Instantiate custom STFT/ISTFT and helper layers.
        self.stft_layer = STFTLayer(frame_length=self.frame_length, frame_step=self.frame_step)
        self.istft_layer = ISTFTLayer(frame_length=self.frame_length, frame_step=self.frame_step, sq_lngth=sq_lngth)
        self.add_inner = AddInnerDim()
        self.squeeze = Squeeze()

        # Layers for processing the magnitude spectrogram.
        self.conv1 = tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu', padding='same')
        self.conv2 = tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu', padding='same')
        self.rnn1 = tf.keras.layers.SimpleRNN(units=sq_lngth//2, activation='relu', return_sequences=True)
        self.dropout = tf.keras.layers.Dropout(0.25)
        self.rnn2 = tf.keras.layers.SimpleRNN(units=sq_lngth//4, activation='relu', return_sequences=True)
        self.dense = tf.keras.layers.Dense(units=self.M_const, activation='linear')

        # Post-ISTFT refinement block:
        # Original pipeline: Conv1D -> SimpleRNN -> Dense -> (residual addition)
        # Now we add an extra SimpleRNN layer before the existing SimpleRNN and a second Conv1D after the Dense.
        self.convout = tf.keras.layers.Conv1D(filters=32, kernel_size=3, activation='relu', padding='same')
        # New additional SimpleRNN layer (rnnout2)
        self.rnnout2 = tf.keras.layers.SimpleRNN(units=32, activation='relu', return_sequences=True)
        # Existing SimpleRNN layer (rnnout)
        self.rnnout = tf.keras.layers.SimpleRNN(units=sq_lngth//2, activation='relu', return_sequences=True)
        # Change denseout to output 1 unit per timestep.
        self.denseout = tf.keras.layers.Dense(units=sq_lngth//2, activation='linear')
        # New additional Conv1D layer (convout2) before adding residual connection.
        self.convout2 = tf.keras.layers.Conv1D(filters=1, kernel_size=3, activation='linear', padding='same')

    def call(self, inputs):
        # inputs: (batch, sq_lngth)
        mag, phase = self.stft_layer(inputs)  # both: (batch, F, T)
        # Crop to M_const time frames.
        mag = mag[:, :, :self.M_const]
        phase = phase[:, :, :self.M_const]
        # Add a singleton channel dimension (for Conv2D)
        mag = self.add_inner(mag)      # (batch, F, T, 1)
        phase = self.add_inner(phase)  # (batch, F, T, 1)

        # Process magnitude with Conv2D layers.
        x = self.conv1(mag)
        x = self.conv2(x)  # x: (batch, F, T, 64)

        batch_size = tf.shape(x)[0]
        # Reshape for RNN: treat frequency dimension (F) as timesteps; flatten T and channels.
        x = tf.reshape(x, [batch_size, self.F_const, self.M_const * 64])  # (batch, F, T*64)

        # Process with two SimpleRNN layers.
        x = self.rnn1(x)
        x = self.dropout(x)
        x = self.rnn2(x)
        # Map each timestep to M_const outputs.
        x = self.dense(x)  # now x: (batch, F, M_const)

        # Process phase: remove channel dimension → (batch, F, M_const)
        phase = self.squeeze(phase)

        # Reconstruct time-domain signal via ISTFT.
        reconstructed = self.istft_layer([x, phase])  # (batch, sq_lngth)

        # === Post-ISTFT refinement block ===
        # Expand dims for Conv1D: (batch, sq_lngth, 1)
        reconstructed = tf.reshape(reconstructed, [batch_size, self.sq_lngth, 1])
        # First Conv1D.
        rec_proc1 = self.convout(reconstructed)  # (batch, sq_lngth, 32)
        # New additional SimpleRNN layer.
        rec_proc = self.rnnout2(rec_proc1)       # (batch, sq_lngth, 32)
        # Existing SimpleRNN layer.
        rec_proc = self.rnnout(rec_proc)          # (batch, sq_lngth, sq_lngth//2)
        # TimeDistributed Dense to map each timestep to 1 feature.
        rec_proc = self.denseout(rec_proc)        # (batch, sq_lngth, 1)
        # New additional Conv1D layer.
        rec_proc = self.convout2(rec_proc)        # (batch, sq_lngth, 1)
        rec_proc = tf.squeeze(rec_proc, axis=-1)  # (batch, sq_lngth)
        # === End refinement block ===

        # Residual connection.
        return inputs + rec_proc

# Now reimplement build_rnn_spectrogram_model using Sequential.
def build_rnn_spectrogram_model(sq_lngth):
    model = tf.keras.Sequential([
        tf.keras.layers.InputLayer(shape=(sq_lngth,)),
        SpectrogramModelLayer(sq_lngth=sq_lngth)
    ])
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
        loss='mse',
        metrics=['mse']
    )
    return model
def main():
    SQNC_LENGTH = 512
    # Example usage:
    # Assume SQNC_LENGTH, samples_sequences_clipped, and samples_sequences are defined.
    model = build_rnn_spectrogram_model(SQNC_LENGTH)
    model.summary()
    early_stopping = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5, restore_best_weights=True)
    batch_size = 512
    train_gen = AudioDataGenerator(wav_file_path, wav_file_path1, SQNC_LENGTH, batch_size=batch_size, shuffle=True)
    steps_per_epoch = (train_gen.nofsamples - SQNC_LENGTH) // (SQNC_LENGTH // 2 * batch_size)
    lr_scheduler = tf.keras.callbacks.LearningRateScheduler(scheduler)
    model.fit(train_gen,
              epochs=10,
              callbacks=[early_stopping,lr_scheduler])

    """Открытие файла который нужно восстановить и получение массива его спектрограмм. file_for_restoration_path - путь к файлу который нужно восстановить.
    samples_input_sequences - массив семплов этого файла

    Zyy,phsy - массивы амплитудных и фазовых спектрограмм файла соответственно
    """

    file_for_restoration_path = "1c.wav"
    samples_input_file = read_wav_as_float(file_for_restoration_path)
    j = 0
    #SQNC_LENGTH = 512
    fs = 44100
    samples_input_sequences = []
    while j < len(samples_input_file ):
        if(j+SQNC_LENGTH < len(samples_input_file)):
            samples_input_sequences.append(samples_input_file[j:j+SQNC_LENGTH])
        j += SQNC_LENGTH
    import numpy as np
    #import tensorflow as tf
    #import matplotlib.pyplot as plt
    #from scipy.signal import stft, istft
    import wave
    # Open the WAV file
    with wave.open(file_for_restoration_path, 'rb') as wav_file:
        fs = wav_file.getframerate()


    """Для правильного восстановления нужны накладывающиеся последовательности семплов исходного файла. Для простоты возьмем степень наложения окон равной 0.5."""

    #print(samples_restored)
    restored_samples_overlap = []
    overlap_input_sequences = []
    step_size = SQNC_LENGTH // 2
    j = 0
    maxv = np.max(np.array(samples_input_file))
    minv = np.min(np.array(samples_input_file))
    while j < len(samples_input_file):
        #print(j, j+SQNC_LENGTH-1)
        if(j+step_size < len(samples_input_file)):
            overlap_input_sequences.append(samples_input_file[j:j+SQNC_LENGTH])
        j += step_size
    for sqnc in overlap_input_sequences:
      if(max(sqnc)>(maxv*0.95) or min(sqnc)<(minv*0.95)):
        elem = np.array(sqnc)
        elem = np.expand_dims(elem, axis=0)  # Now shape is (1, SQNC_LENGTH)
        res = model.predict(elem,verbose=0).flatten()
        #print(res[SQNC_LENGTH//4:(SQNC_LENGTH*3)//4])
        restored_samples_overlap.append(res[SQNC_LENGTH//4:(SQNC_LENGTH*3)//4])
      else:
        restored_samples_overlap.append(np.array(sqnc[SQNC_LENGTH//4:(SQNC_LENGTH*3)//4]))

    restored_samples_overlap = np.array(restored_samples_overlap).flatten()
    #print(type(restored_samples_overlap))
    print(restored_samples_overlap.shape)

    """Если мы хотим произвести сравнение с каким-либо другим методом, возможно, возникнет проблема из-за разных длин файлов: текущий алгоритм отбрасывает последние сэмплы в файле чтобы достичь количества сэмплов кратного SQNC_LENGTH. Если раскомментировать вторую строку мы получим массив в котором недостающие восстановленные сэмплы заменены сэмплами исходного массива до требуемой длины, что обеспечит возможность сравнения файлов. output_path - название файла, в который будет записан вывод программы."""

    #samples_restored_final = samples_restored
    #for i in range(len(samples_restored_final)):
      #print(type(samples_restored_final),len(samples_restored_final[i]))
    import wave
    import numpy as np

    def write_float_samples_to_wav(samples, sample_rate, output_path):
        """
        Writes floating-point audio samples to a mono 16-bit WAV file.

        Parameters:
            samples (list or np.ndarray): Array of floating-point audio samples in the range [-1.0, 1.0].
            sample_rate (int): Sample rate of the audio in Hz (e.g., 44100).
            output_path (str): Path to save the output WAV file.
        """
        # Ensure the samples are a NumPy array
        samples = np.array(samples, dtype=np.float32)

        # Clip the samples to the range [-1.0, 1.0] to prevent overflow
        samples = np.clip(samples, -1.0, 1.0)

        # Convert to 16-bit PCM format
        int_samples = (samples * 32767).astype(np.int16)

        # Write to a WAV file
        with wave.open(output_path, 'wb') as wav_file:
            # Set the parameters for the WAV file
            wav_file.setnchannels(1)  # Mono
            wav_file.setsampwidth(2)  # 16-bit PCM
            wav_file.setframerate(sample_rate)

            # Write the audio frames
            wav_file.writeframes(int_samples.tobytes())

    output_path = 'output.wav'  # Path to save the WAV file

    #write_float_samples_to_wav(samples_restored_final, fs, output_path)
    #print(f"WAV file written to {output_path}")
    restored_samples_overlap = np.array(restored_samples_overlap).flatten()
    restored_samples_overlap = np.append(np.array(samples_input_file[0:SQNC_LENGTH//4]),restored_samples_overlap)
    restored_samples_overlap = np.append(restored_samples_overlap,np.array(samples_input_file[-SQNC_LENGTH//4:]))
    write_float_samples_to_wav(restored_samples_overlap, fs, output_path)
    print(f"WAV file written to {output_path}")

    model.save("clipping_interpolation_model.keras")
    
if __name__ == '__main__':
    main()
